2022-04-29 18:39:45.182 [Info] Discovered 0 plugins:


--------------------------------------------------------------------------------
2022-04-29 18:39:46.325 [Info] Connecting to 38.129.153.213:5400...

--------------------------------------------------------------------------------
2022-04-29 18:39:46.752 [Info] Connection approved [00000000-0000-0000-0000-000000000000].

--------------------------------------------------------------------------------
2022-04-29 18:39:46.820 [Debug] approval Time=5451974 Offset=63786848934761 Real=63786854386736

--------------------------------------------------------------------------------
2022-04-29 18:39:46.821 [Debug] local Time=5451974 Offset=63786848934845 Real=63786854386820

--------------------------------------------------------------------------------
2022-04-29 18:39:46.821 [Debug] real delta=83

--------------------------------------------------------------------------------
2022-04-29 18:39:46.821 [Debug] this.Statistics.Ping=0 NCPing=7

--------------------------------------------------------------------------------
2022-04-29 18:39:46.823 [Debug] Connection established to remote [00000000-0000-0000-0000-000000000000/38.129.153.213:5400].

--------------------------------------------------------------------------------
2022-04-29 18:39:46.823 [Info] Connected [00000000-0000-0000-0000-000000000000].

--------------------------------------------------------------------------------
2022-04-29 18:39:58.899 [Warn] 'Me' is null.

--------------------------------------------------------------------------------
2022-04-29 18:39:59.114 [Error] Received unhandled exception from Name:Intersect Client.exe
There are no context policies.
.

--------------------------------------------------------------------------------
2022-04-29 18:39:59.115 [Error] NullReferenceException: Object reference not set to an instance of an object.
    Stack:    at Intersect.Client.Interface.Debugging.DebugWindow.<>c.<CreateTableDebugStats>b__29_14(Base x)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Intersect.Client.Interface.Debugging.DebugWindow.<>c.<CreateTableDebugStats>b__29_13(CancellationToken cancellationToken)
   at Intersect.Client.Framework.Gwen.Control.Data.ValueTableCellDataProvider`1.<>c__DisplayClass1_1.<.ctor>b__3(Task _)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Intersect.Async.AsyncValueGenerator`1.<DoLoop>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


--------------------------------------------------------------------------------
2022-04-29 18:39:59.126 [Info] Acquiring context lock... (0ms)

--------------------------------------------------------------------------------
2022-04-29 18:39:59.126 [Info] Acquired. (0ms)

--------------------------------------------------------------------------------
2022-04-29 18:39:59.127 [Info] Beginning context dispose. (0ms)

--------------------------------------------------------------------------------
2022-04-29 18:39:59.128 [Info] GC.SuppressFinalize (0ms)

--------------------------------------------------------------------------------
2022-04-29 18:39:59.128 [Info] InternalDispose() completed. (0ms)

--------------------------------------------------------------------------------
2022-04-29 18:39:59.128 [Info] Clearing instance... (1ms)

--------------------------------------------------------------------------------
2022-04-29 18:39:59.128 [Info] Releasing context lock... (1ms)

--------------------------------------------------------------------------------
2022-04-29 18:39:59.128 [Info] Released. (1ms)

--------------------------------------------------------------------------------
2022-04-29 18:39:59.215 [Debug] received epp: 5464101

--------------------------------------------------------------------------------
